      containers:
        - name: rails
          image: vishal933/myrailsapp:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_HOST
              value: postgres
            - name: DATABASE_USERNAME
              value: myuser
            - name: DATABASE_PASSWORD
              value: mypassword
            - name: DATABASE_NAME
              value: myapp_production
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
