apiVersion: v1
kind: Service
metadata:
  name: rails-service
spec:
  selector:
    app: rails   # ✅ This must match the deployment label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
